FROM ubuntu:24.04

ENV ROS_DISTRO=jazzy
ENV AMENT_PREFIX_PATH=/opt/ros/${ROS_DISTRO}
ENV COLCON_PREFIX_PATH=/opt/ros/${ROS_DISTRO}
ENV LD_LIBRARY_PATH=/opt/ros/${ROS_DISTRO}/lib
ENV PATH=/opt/ros/${ROS_DISTRO}/bin:$PATH
ENV PYTHONPATH=/opt/ros/${ROS_DISTRO}/lib/python3.10/site-packages
ENV ROS_PYTHON_VERSION=3
ENV ROS_VERSION=2

ENV TZ=Asia/Singapore

RUN apt update && apt install curl -y
RUN apt install -y --no-install-recommends tzdata

RUN curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/1.2.0/ros2-apt-source_1.2.0.noble_all.deb"
RUN dpkg -i /tmp/ros2-apt-source.deb

RUN apt update
RUN apt install ros-dev-tools -y
RUN apt update && apt upgrade -y
RUN apt install -y ros-${ROS_DISTRO}-desktop


RUN apt install -y ros-${ROS_DISTRO}-xacro ros-${ROS_DISTRO}-turtlesim ros-${ROS_DISTRO}-joint-state-publisher-gui ros-${ROS_DISTRO}-turtlebot3 ros-${ROS_DISTRO}-turtlebot3-simulations ros-${ROS_DISTRO}-gz-ros2-control ros-${ROS_DISTRO}-rqt-graph ros-${ROS_DISTRO}-rqt 
#COPY ./tb3_navigation2.rviz /opt/ros/${ROS_DISTRO}/share/turtlebot3_navigation2/rviz/tb3_navigation2.rviz

RUN echo "export DISPLAY=host.docker.internal:0.0" >> ~/.bashrc
RUN echo "export TURTLEBOT3_MODEL=burger" >> ~/.bashrc
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc
RUN echo "source /root/dev_ws/install/setup.bash" >> ~/.bashrc

RUN echo "echo '------------------------------------------------'" >> ~/.bashrc
RUN echo "echo '| MAKE SURE IN dev_ws BEFORE colcon build:     |'" >> ~/.bashrc
RUN echo "echo '|   cd ~/dev_ws                                |'" >> ~/.bashrc
RUN echo "echo '|   colcon build                               |'" >> ~/.bashrc
RUN echo "echo '| AFTER BUILT, MAKE SURE source THE setup.bash |'" >> ~/.bashrc
RUN echo "echo '|   source ~/dev_ws/install/setup.bash         |'" >> ~/.bashrc
RUN echo "echo '------------------------------------------------'" >> ~/.bashrc

WORKDIR /root
